version: '3'

services:
  web:
    image: yerldsho/app1:latest
    #build: ./web
    #command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/web_django
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    image: mariadb
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'myproject2'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    restart: on-failure
    volumes:
      - ./db_django:/var/lib/mysql

